version: 2
ethernets:
  ${INTERFACE}:
    addresses:
      - ${IP_ADDR}/24
    dhcp4: false
    gateway4: 192.168.122.1
    match:
      macaddress: ${MAC_ADDR}
    nameservers:
      addresses:
        - 1.1.1.1
        - 8.8.8.8
    set-name: ${INTERFACE}
