#cloud-config
hostname: ${VM_NAME}
manage_etc_hosts: true
users:
  - name: ${VM_USERNAME}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/${VM_USERNAME}
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
    ${VM_USERNAME}:${VM_PASSWORD}
  expire: false
write_files:
  - path: /etc/environment
    content: |
      http_proxy="${HTTP_PROXY}"
      https_proxy="${HTTP_PROXY}"
      no_proxy="${NO_PROXY}"
      HTTP_PROXY="${HTTP_PROXY}"
      HTTPS_PROXY="${HTTP_PROXY}"
      NO_PROXY="${NO_PROXY}"
  - path: /etc/apt/apt.conf.d/95proxies
    content: |
      Acquire::http::Proxy "${HTTP_PROXY}";
      Acquire::https::Proxy "${HTTP_PROXY}";
runcmd:
  - echo 'Defaults env_keep+="http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY"' >> /etc/sudoers
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y ubuntu-drivers-common
  - ubuntu-drivers autoinstall
  - reboot
